#!/usr/bin/env ruby
#
# Generates a SFV file from the filename.
#
# Since anime fansubs usually add the CRC32 checksum to the end of the filename,
# but don't always make a SFV file available, I decided to create a simple
# script that extracts those checksums. One can pipe the output of this script
# to a file and then check the checksums with a common SFV checker.
#
# (C)opyright 2009 Ricardo Martins <ricardo at scarybox dot net>
# Licensed under the MIT/X11 License. See LICENSE file for license details.

require 'date'

def getCRC32(filename)
    filename.match(/\[([a-zA-Z0-9]{8})\]/).captures.last
end

def header
    now = DateTime.now
    "; Generated by generate_sfv v0.1 on #{now.year}-#{now.month}-#{now.day} \
    at #{now.hour}:#{now.min}:#{now.sec}"
end

def main
    puts header

    #files = Dir.entries(".").sort - [".", ".."]
    files = ARGV
    files.each do |filename|
        puts filename + " " + getCRC32(filename)
    end
end

main
